## Using the classificaction methods with features extracted from FIR filtered signals 

In [1]:
#imports
import numpy as np
import matplotlib.pyplot as plt
import scipy.signal as sig
from scipy.io import loadmat

#matplotlib in separate window
%matplotlib qt5

In [3]:
# carregar sinais e separar data e target
eeg = loadmat('/home/renato/Dropbox/Mestrado/final/kolodziej_dataset/dataset_15_canais.mat')
data = eeg['data']
target = eeg['target'].reshape((data.shape[0])) # mudando a dimensão do shape do vetor target
fs = 256.
fn = fs / 2.

# projetar banco de filtros

# aplicar os filtros aos sinais 
# criar os estimadores
# utilizar os sinais filtrados como entrada para os estimadores 

In [4]:
# sinal de teste
test_signal = data[0]
freq = np.array([10, 20])
# projetando banco de filtros 
# filt = sig.firwin(1001, cutoff=freq/fn, window='hamming', pass_zero=False)
x  = sig.freqz(filt)

NameError: name 'filt' is not defined

In [5]:
def design_butter_fir(cutoff, fs, order=101, band='pass', window='hamming'):
    import numpy as np
    import scipy.signal as sig

    fs = float(fs)
    fnyq = fs / 2
    cutoff = np.array(cutoff) / fnyq

    if order % 2 == 0:
        order = order + 1

    if band == 'pass':
        pass_zero = False
    elif band == 'stop':
        pass_zero = True
    else:
        print('ERROR')

    coeff = sig.firwin(order, cutoff, pass_zero=pass_zero, window=window)
    freq_vec, imp_vec = sig.freqz(coeff, 1.)

    return coeff, freq_vec, imp_vec


def generate_harmonics(freq, n_harmonics):
    import numpy as np
    harmonics = [(i * (j + 1)) for i in freq for j in range(n_harmonics)]
    harmonics = np.array(harmonics)

    return harmonics.reshape(len(freq), n_harmonics)


def generate_band_tolerance(freq, tol):
    import numpy as np
    freq = np.array(freq)
    f1 = freq + tol
    f2 = freq - tol
    freq_tol = [[f1[i][j], f2[i][j]] for i in range(len(f1[0]) for j in range(len(f2[0])))]

    return np.array(freq_tol)




In [6]:
fr = generate_harmonics([5,6,7,8], 4) 
tol = 0.2
freq = np.array(fr)
f1 = freq + tol
f2 = freq - tol

x = [[i-tol, i+tol] for i in fr]
y = [x[0][i][j] for j in range(4) for i in range(2)]
# [(k,i,j)for k in range(4) for j in range(4) for i in range(2)]
y = np.array(y)
y

array([  4.8,   5.2,   9.8,  10.2,  14.8,  15.2,  19.8,  20.2])

In [7]:
t = generate_harmonics([5,6,7,8], 4)
print(len(t))

x = [[i-tol, i+tol] for i in t]
for m in range(len(t)):
    y = [x[m][i][j] for j in range(4) for i in range(2)]
    
y = np.array(y)
y

4


array([  7.8,   8.2,  15.8,  16.2,  23.8,  24.2,  31.8,  32.2])

In [8]:
x = fr[0] 
tol = .2
fs = 256.
fn = fs / 2
z = np.hstack(np.array([[x[i]-tol, x[i]+tol] for i in range(len(x))]))

y = design_butter_fir(order=401, cutoff=z, fs=256.)
# plt.plot((fn/np.pi)*y[1],20*np.log10(np.abs(y[2])))
z

array([  4.8,   5.2,   9.8,  10.2,  14.8,  15.2,  19.8,  20.2])

In [10]:
freq = generate_harmonics([5,6,7,8],4)
generate_band_tolerance(freq, 0.3)

TypeError: 'generator' object cannot be interpreted as an integer